version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: deadlock_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: deadlock_tierlist
    ports:
      - "5432:5432"
    volumes:
      - deadlock_pg_data:/var/lib/postgresql/data

  app:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    
    # Replace [YOUR_DOCKER_USER] with your actual username
    image: [YOUR_DOCKER_USER]/deadlock-tierlist:latest
    container_name: deadlock_app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgrespassword@db:5432/deadlock_tierlist
    depends_on:
      - db
    restart: always

volumes:
  deadlock_pg_data:
